sudo: required
services:
  - docker
before_install:
  - docker build -t dahyor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dahyor/react-test npm test -- --watchAll=false

after_success:
  - docker build -t dahyor/multi-client ./client
  - docker build -t dahyor/multi-server ./server
  - docker build -t dahyor/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dahyor/multi-client
  - docker push dahyor/multi-server
  - docker push dahyor/multi-worker
  # - docker build -t dahyor/multi-nginx ./server

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-516128361868"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"